### ISSUE TITLE
Working with cohttp 4.0.0

### ISSUE THREAD

**Issue by Fourchaux** [yannham/mechaml#5]
(OCaml 4.12.0)

Installing mechaml downgrade cohttp from 4.0.0 to 2.5.5.

Would it be possible to update the library to work with cohttp 4.0.0?

TY

**Comment by yannham** [comment]
I haven't updated the dependencies in a while, so that's fair! Will take a look when I have spare time.

**Comment by yannham** [comment]
https://github.com/ocaml/opam-repository/pull/18641

**Comment by yannham** [comment]
Merged in ~~opal~~ opam.
