### ISSUE TITLE
single page applications?

### ISSUE THREAD

**Issue by geofflangenderfer** [yannham/mechaml#7]
Can this library handle pages with lots of javascript to be executed?

Puppeteer handles this `evaluate()`
```javascript
// npm i puppeteer
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  // let's navigate to the dev.to homepage
  await page.goto('https://dev.to');

  // evaluate will run the function in the page context
  await page.evaluate(_ => {
    // this will be executed within the page, that was loaded before
    document.body.style.background = '#000';
  });

  // and let's take a screenshot
  await page.screenshot({
    path: 'home.png',
  });

  // we're done; close the browser
  await browser.close();
})();
```

**Comment by yannham** [comment]
No, Mechaml uses a simple stand-alone HTTP client (cohttp), thus it is not able to execute JavaScript. Puppeteer, on the other hand, uses a full-fledged instance of Chrome. There is [bs-puppeteer](https://github.com/zploskey/bs-puppeteer), bindings for ReasonML that let you to write scraping code using puppeteer in ReasonML (Reason is just OCaml for the web with a slightly different syntax), but it needs to be compiled to javascript via bucklescript to be run. I am not aware of a native OCaml library that handles JavaScript. It is possible in theory to do the same as puppeteer using the Chrome DevTools protocol, but it probably requires quite a lot of work.

**Comment by geofflangenderfer** [comment]
bs-puppeteer looks great. Thanks!
